# Challenge 2

# 1. Find the size, the shape, and the number of dimension of the following array:

a. [[[[2,3,4],[7.8.9]],[[2,3,4],[7.8.9]]]]

b. [[[2,3,4]],[[7.8.9]]]

c. [[[[[2.0,4.6],[2.0,4.6],[2.0,4.6]],[[2.0,4.6],[2.0,4.6],[2.0,4.6]]]]]

In [8]:
import numpy as np
a = np.array([[[[2,3,4],[7,8,9]],[[2,3,4],[7,8.,9]]]])
b = np.array([[[2,3,4]],[[7,8,9]]])
c = np.array([[[[[2.0,4.6],[2.0,4.6],[2.0,4.6]],[[2.0,4.6],[2.0,4.6],[2.0,4.6]]]]])

print("a ----- size : ", a.size, "\t shape : ", a.shape, "\t dimension : ", a.ndim, "\n  ", a, "\n  ")
print("b ----- size : ", b.size, "\t shape : ", b.shape, "\t dimension : ", b.ndim, "\n  ", b, "\n  ")
print("c ----- size : ", c.size, "\t shape : ", c.shape, "\t dimension : ", c.ndim, "\n  ", c, "\n  ")



a ----- size :  12 	 shape :  (1, 2, 2, 3) 	 dimension :  4 
   [[[[2. 3. 4.]
   [7. 8. 9.]]

  [[2. 3. 4.]
   [7. 8. 9.]]]] 
  
b ----- size :  6 	 shape :  (2, 1, 3) 	 dimension :  3 
   [[[2 3 4]]

 [[7 8 9]]] 
  
c ----- size :  12 	 shape :  (1, 1, 2, 3, 2) 	 dimension :  5 
   [[[[[2.  4.6]
    [2.  4.6]
    [2.  4.6]]

   [[2.  4.6]
    [2.  4.6]
    [2.  4.6]]]]] 
  


# 2. Create the following arrays:

a. 3-D array of three 2 by 2 innermost array with zero values

b. 4-D array of three 2 by 2 innermost array with zero values

c. 3-D  array of one 2 by 5 innermost array with the value of one throughout

d. 4-D array of two 3 by 3 innermost array with the value of one throughout

e. 5-D array of two 2 by 2 innermost array with the value of one throughout

f. 8-D array of four 2 by 2 innermost with the value of one throughout

In [20]:
print("a = 3-D array of three 2 by 2 innermost array with zero values")
a = np.zeros((3,2,2))
print(a,"\n")

print("b = 4-D array of three 2 by 2 innermost array with zero values")
b = np.zeros((1,3,2,2))
print(b,"\n")

print("c = 3-D  array of one 2 by 5 innermost array with the value of one throughout")
c =np.ones((1,2,5))
print(c,"\n")

print("d = 4-D array of two 3 by 3 innermost array with the value of one throughout")
d = np.ones((1,2,3,3))
print(d,"\n")

print("e = 5-D array of two 2 by 2 innermost array with the value of one throughout")
e=np.ones((1,1,2,2,2))
print(e,"\n")

print("f = 8-D array of four 2 by 2 innermost with the value of one throughout")
f= np.ones((1,1,1,1,1,4,2,2))
print(f,"\n")

a = 3-D array of three 2 by 2 innermost array with zero values
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]] 

b = 4-D array of three 2 by 2 innermost array with zero values
[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]] 

c = 3-D  array of one 2 by 5 innermost array with the value of one throughout
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]] 

d = 4-D array of two 3 by 3 innermost array with the value of one throughout
[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]] 

e = 5-D array of two 2 by 2 innermost array with the value of one throughout
[[[[[1. 1.]
    [1. 1.]]

   [[1. 1.]
    [1. 1.]]]]] 

f = 8-D array of four 2 by 2 innermost with the value of one throughout
[[[[[[[[1. 1.]
       [1. 1.]]

      [[1. 1.]
       [1. 1.]]

      [[1. 1.]
       [1. 1.]]

      [[1. 1.]
       [1. 1.]]]]]]]] 



# 3. Create a 1D arary with values from 100 to 200 with a step of 10

In [24]:
x = np.arange(100, 200, 10)
x

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

# 4. Create a 1D array with 5 values from 5 to 25

In [30]:
y = np.linspace(5, 25, num=5)
print(y,"\n or\n")
print (y.reshape(5,1))


[ 5. 10. 15. 20. 25.] 
 or

[[ 5.]
 [10.]
 [15.]
 [20.]
 [25.]]
