# Challenge 1

# 1. Look at the following and describe the type of array each will create before running the code.



a = np.array([3,6,7,8,9])

b = np.array([[7,8,9,3],[4,6,7,8]])

c = np.array([[[[7,8,9,3],[4,6,7,8]]]])

d = np.array([[[7,8,9,3],[4,6,7,8]], [[2,1,3,6],[1,7,9,10]]])

e = np.array([[7,8,9,3],[4,6,7,8],[2,1,3,6],[1,7,9,10]])

In [1]:
import numpy as np
a = np.array([3,6,7,8,9])
b = np.array([[7,8,9,3],[4,6,7,8]])
c = np.array([[[[7,8,9,3],[4,6,7,8]]]])
d = np.array([[[7,8,9,3],[4,6,7,8]], [[2,1,3,6],[1,7,9,10]]])
e = np.array([[7,8,9,3],[4,6,7,8],[2,1,3,6],[1,7,9,10]])

print("Dimension de a : ",a.ndim,  " \n ", a,  "\n ")
print("Dimension de b : ",b.ndim,  " \n ", b, "\n ")
print("Dimension de c : ",c.ndim,  " \n ", c, "\n ")
print("Dimension de d : ",d.ndim,  " \n ", d, "\n ")
print("Dimension de e: ",e.ndim,  " \n ", e, "\n ")


Dimension de a :  1  
  [3 6 7 8 9] 
 
Dimension de b :  2  
  [[7 8 9 3]
 [4 6 7 8]] 
 
Dimension de c :  4  
  [[[[7 8 9 3]
   [4 6 7 8]]]] 
 
Dimension de d :  3  
  [[[ 7  8  9  3]
  [ 4  6  7  8]]

 [[ 2  1  3  6]
  [ 1  7  9 10]]] 
 
Dimension de e:  2  
  [[ 7  8  9  3]
 [ 4  6  7  8]
 [ 2  1  3  6]
 [ 1  7  9 10]] 
 


# 2. Using 4,6,7,8,2 help create the following (repetition of data is allowed):



a. 1-D array

b. 2-D array

c. 2-D array with three 2-D array

d. 5-D array with one 1-D array

e. 5-D array with two 1-D array

f. 5-D array with two 3-D array

In [22]:
a = np.array([4,6,7,8,2])
print("a = 1D array : \n",a,"\n")

b = np.array([[7,8,9,2],[4,6,7,8]])
print("b = 2D array : \n",b,"\n")

print("c = 2D array with 3 2D array: IMPOSSIBLE\n")

d = np.array([[[[[7,8,9,2]]]]])
print("d = 5D array with 1 1D array : \n",d,"\n")

e = np.array([[[[[7,8,9,2],[7,8,9,2]]]]])
print("e = 5D array with 2 1D array : \n",e,"\n")

f = np.array([[[[[7,8,9,2]]],[[[7,8,9,2]]]]])
print("f = 5D array with 2 3D array : \n",f,"\n")

a = 1D array : 
 [4 6 7 8 2] 

b = 2D array : 
 [[7 8 9 2]
 [4 6 7 8]] 

c = 2D array with 3 2D array: IMPOSSIBLE

d = 5D array with 1 1D array : 
 [[[[[7 8 9 2]]]]] 

e = 5D array with 2 1D array : 
 [[[[[7 8 9 2]
    [7 8 9 2]]]]] 

f = 5D array with 2 3D array : 
 [[[[[7 8 9 2]]]


  [[[7 8 9 2]]]]] 

